### ISSUE TITLE
How about the 1-st stage training?

### ISSUE THREAD

**Issue by Vincent-ZHQ** [thuhcsi/SECap#6]
Thank you for your sharing of the implementation. Will you have a plan to release the code of 1st stage training?

**Comment by xuyaoxun** [comment]
Thank you for your interest in our work. Regarding the release plan for the code of the 1st stage training, please refer to this Issue [https://github.com/thuhcsi/SECap/issues/2](https://github.com/thuhcsi/SECap/issues/2) for more details.
