### ISSUE TITLE
inference error when loading statedict

### ISSUE THREAD

**Issue by MisakaMikoto96** [thuhcsi/SECap#7]
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MotionAudio:
	Unexpected key(s) in state_dict: "text2vec_model.embeddings.position_ids". 

weights has prepared

**Comment by cythc** [comment]
same problem

**Comment by MisakaMikoto96** [comment]
> same problem

Hi, I download the original model on: https://huggingface.co/shibing624/text2vec-base-chinese/tree/main and make sure that your transformer==4.29.0. It works. 

FYI.
